version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-posts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a8shjjuanmdd"
s3_prefix = "get-posts"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
